// jsPDF is imported dynamically inside downloadResultAsPdf() below,
// rather than at module load — it's only needed when the person
// actually clicks "Download PDF", so it shouldn't be part of every
// page's initial bundle.

const MARGIN = 48
const PAGE_WIDTH = 595.28 // A4 at 72dpi points
const PAGE_HEIGHT = 841.89
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2

const SEVERITY_LABEL = { low: 'Low', medium: 'Medium', high: 'High' }

export async function downloadResultAsPdf(result) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  let y = MARGIN

  const ensureSpace = (needed) => {
    if (y + needed > PAGE_HEIGHT - MARGIN) {
      doc.addPage()
      y = MARGIN
    }
  }

  const writeParagraph = (text, { fontSize = 11, font = 'normal', color = '#1a1a1a', gapAfter = 14 } = {}) => {
    doc.setFont('helvetica', font)
    doc.setFontSize(fontSize)
    doc.setTextColor(color)
    const lines = doc.splitTextToSize(text, CONTENT_WIDTH)
    lines.forEach((line) => {
      ensureSpace(fontSize + 4)
      doc.text(line, MARGIN, y)
      y += fontSize + 4
    })
    y += gapAfter
  }

  const writeHeading = (text) => {
    ensureSpace(30)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor('#111111')
    doc.text(text, MARGIN, y)
    y += 8
    doc.setDrawColor('#e0a458')
    doc.setLineWidth(1)
    doc.line(MARGIN, y, MARGIN + CONTENT_WIDTH, y)
    y += 16
  }

  // Title block
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor('#111111')
  doc.text(result.documentType || 'Document', MARGIN, y)
  y += 20

  if (result.documentName) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor('#666666')
    doc.text(result.documentName, MARGIN, y)
    y += 24
  } else {
    y += 10
  }

  // Summary
  if (result.summary) {
    writeHeading('Summary')
    writeParagraph(result.summary)
  }

  // Key terms
  if (result.keyTerms?.length) {
    writeHeading('Key Terms')
    result.keyTerms.forEach((term) => writeParagraph(`•  ${term}`, { gapAfter: 6 }))
    y += 8
  }

  // Red flags
  if (result.redFlags?.length) {
    writeHeading('Worth Double-Checking')
    result.redFlags.forEach((flag) => {
      const label = SEVERITY_LABEL[flag.severity] || 'Note'
      writeParagraph(`[${label}] ${flag.issue}`, { font: 'bold', gapAfter: 4 })
      const reason = flag.why_it_matters || flag.whyItMatters
      if (reason) writeParagraph(reason, { fontSize: 10, color: '#444444', gapAfter: 12 })
    })
  }

  // Action items
  if (result.actionItems?.length) {
    writeHeading('What To Do Next')
    result.actionItems.forEach((item) => writeParagraph(`•  ${item}`, { gapAfter: 6 }))
  }

  // Footer on every page
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor('#999999')
    doc.text('Generated by Doculyze — not professional or legal advice.', MARGIN, PAGE_HEIGHT - 24)
    doc.text(`${i} / ${pageCount}`, PAGE_WIDTH - MARGIN - 24, PAGE_HEIGHT - 24)
  }

  const safeName = (result.documentName || result.documentType || 'document').replace(/[^a-z0-9]+/gi, '-').toLowerCase()
  doc.save(`doculyze-${safeName}.pdf`)
}
